apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eng2role
  namespace: keduit
rules:
- apiGroups: ["apps", ""]
  resources: ["pods", "deployments"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eng2role
  namespace: keduit
roleRef:
  kind: Role
  name: eng2role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eng2
  namespace: keduit